version: '3.8'

services:

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: app_container
    ports:
      - 3000:3000
    networks:
      - node_monitoring
    

  prometheus:
    image: prom/prometheus
    container_name: prometheus_container
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_storage:/prometheus
    networks:
      - node_monitoring

  
volumes:
  prometheus_storage:

networks:
  node_monitoring: