global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'application-metrics'
    static_configs:
      - targets: ['app_container:3000']

  
  - job_name: 'loki-logs'
    static_configs:
      - targets: ['loki_container:3100']